### ISSUE TITLE
Version Issues 

### ISSUE THREAD

**Issue by pratham-0709** [jhuapl-boss/boss-oidc2#4]
When Implementing this, You have mentioned bossoidc.settings in the settings.py file, So when running the tests it says that bossoidc module not found , when installing bossoidc module it downgrades the version of Django which creates a conflicts in my scripts .. 

![Screenshot 2023-02-01 104423](https://user-images.githubusercontent.com/53365574/215959826-cba16004-6e9e-4295-9477-96051c59d28b.png)

As you can see in the image "Path" is used in Django 3.0+ and when installed bossoidc it downgrades Django1.0 , due to which it creates conflicts in scripts , try to overview the issue 

Can Provide A Proper Implementation of this .

**Comment by movestill** [comment]
I'm sorry to hear you're having issues. However, we do not currently support Django 3.x.
